.TH "engine.Engine" 3 "Tue Jun 2 2020" "Version 1.0" "Licenser" \" -*- nroff -*-
.ad l
.nh
.SH NAME
engine.Engine \- Does the licensing\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, file_name, project_path)"
.br
.RI "Constructor\&. "
.ti -1c
.RI "def \fBlicense\fP (self)"
.br
.RI "Does the licensing\&. "
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBsettings\fP"
.br
.RI "File containg the settings\&. "
.ti -1c
.RI "\fBproject\fP"
.br
.RI "List of files to ignore\&. "
.in -1c
.SH "Detailed Description"
.PP 
Does the licensing\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def engine\&.Engine\&.__init__ ( self,  file_name,  project_path)"

.PP
Constructor\&. 
.PP
\fBParameters\fP
.RS 4
\fIfile_name\fP Settings file 
.br
\fIproject_path\fP The path of the project 
.RE
.PP

.SH "Member Data Documentation"
.PP 
.SS "engine\&.Engine\&.project"

.PP
List of files to ignore\&. Path to the project 

.SH "Author"
.PP 
Generated automatically by Doxygen for Licenser from the source code\&.
