.TH "utils" 3 "Tue Jun 2 2020" "Version 1.0" "Licenser" \" -*- nroff -*-
.ad l
.nh
.SH NAME
utils
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBline_prepender\fP (filename, text)"
.br
.RI "Adds content at the start of a file\&. "
.ti -1c
.RI "def \fBget_content\fP (filename)"
.br
.RI "Gets content from a file\&. "
.in -1c
.SH "Detailed Description"
.PP 
Contains utility functions 
.SH "Function Documentation"
.PP 
.SS "def utils\&.get_content ( filename)"

.PP
Gets content from a file\&. 
.PP
\fBParameters\fP
.RS 4
\fIfilename\fP The file 
.RE
.PP

.SS "def utils\&.line_prepender ( filename,  text)"

.PP
Adds content at the start of a file\&. 
.PP
\fBParameters\fP
.RS 4
\fIfilename\fP The file 
.br
\fItext\fP Content to be added 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Licenser from the source code\&.
